export const TOKEN_KEY = 'grs_gh_token'
export const GITHUB_API = 'https://api.github.com/graphql'
export const GITHUB_API_V3 = 'https://api.github.com/repos/'
export const REPO_STATS_CLASS = 'numbers-summary'
export const REPO_REFRESH_STATS_QUERY = '.repository-content .Box .Details ul'
export const REPO_SIZE_ID = 'addon-repo-size'
export const SIZE_KILO = 1024
export const UNITS = ['B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB']
export const AUTO_ASK_KEY = 'grs_auto_ask'
export const MODAL_ID = 'grs_token_modal'
export const TOKEN_INPUT_ID = 'grs_token_input'
